
groups:
  - name: Group 1
    commands:
      - name: Command Name
        command: echo hello
        prompt: true
  - name: Group 2
    commands:
      - name: Command 2-1
        command: kite app info
        prompt: true
      - name: Command 2-2
        command: kite app info
        prompt: false
  - name: Jenkins dev
    commands:
      - name: provider build
        prompt: true
        command: |
          kite http tpl-send -d jenkins --api hook-build -e dev-provider --vv -v group=java-group -v branch=qa -v repoName=common-provider
  
